name: CI

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install



      - name: Set permissions for all bin scripts
        run: chmod +x ./node_modules/.bin/*
      
      - name: Run Jest
        run: npx jest --detectOpenHandles --forceExit

 delivery:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() }}

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Checkout main branch
        run: git checkout main

      - name: Merge develop into main
        run: |
          git merge --no-ff origin/develop
          git push origin main