name: Continuous Integration

on: pull_request

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Especifique a versão do Node.js adequada ao seu projeto

      - name: Set execute permissions for Jest
        run: chmod +x node_modules/.bin/jest

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
