

name: CI


on:
  push:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:

  build:
    
    runs-on: ubuntu-latest

    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Run Jest
        run: npm test
          
  delivery:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      
      - name: Merge to main
        run: |
          git fetch
          git checkout main
          git merge develop --allow-unrelated-histories --no-edit
          git push origin main