name: CI

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Sets up the Node.js environment
      - uses: actions/setup-node@v2
        with:
          node-version: '21'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run Jest tests using npx
      - name: Run Jest
        run: npx jest --detectOpenHandles

  delivery:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      # Set up Git
      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      
      # Merge develop into main
      - name: Merge to main
        run: |
          git fetch
          git checkout main
          git merge develop --allow-unrelated-histories --no-edit
          git push origin main
